# https://s1.hdslb.com/bfs/static/jinkela/long/font/regular.css

curl -O https://s1.hdslb.com/bfs/static/jinkela/long/font/HarmonyOS_Regular.a.woff2
curl -O https://s1.hdslb.com/bfs/static/jinkela/long/font/HarmonyOS_Regular.b.woff2
curl -O https://s1.hdslb.com/bfs/static/jinkela/long/font/HarmonyOS_Regular.c.woff2
curl -O https://s1.hdslb.com/bfs/static/jinkela/long/font/HarmonyOS_Regular.d.woff2
curl -O https://s1.hdslb.com/bfs/static/jinkela/long/font/HarmonyOS_Regular.e.woff2
curl -O https://s1.hdslb.com/bfs/static/jinkela/long/font/HarmonyOS_Regular.f.woff2
curl -O https://s1.hdslb.com/bfs/static/jinkela/long/font/HarmonyOS_Regular.g.woff2
curl -O https://s1.hdslb.com/bfs/static/jinkela/long/font/HarmonyOS_Regular.h.woff2
curl -O https://s1.hdslb.com/bfs/static/jinkela/long/font/HarmonyOS_Regular.i.woff2
curl -O https://s1.hdslb.com/bfs/static/jinkela/long/font/HarmonyOS_Regular.j.woff2
curl -O https://s1.hdslb.com/bfs/static/jinkela/long/font/HarmonyOS_Regular.k.woff2
curl -O https://s1.hdslb.com/bfs/static/jinkela/long/font/HarmonyOS_Regular.l.woff2
curl -O https://s1.hdslb.com/bfs/static/jinkela/long/font/HarmonyOS_Regular.m.woff2
curl -O https://s1.hdslb.com/bfs/static/jinkela/long/font/HarmonyOS_Regular.n.woff2
curl -O https://s1.hdslb.com/bfs/static/jinkela/long/font/HarmonyOS_Regular.o.woff2
curl -O https://s1.hdslb.com/bfs/static/jinkela/long/font/HarmonyOS_Regular.p.woff2
curl -O https://s1.hdslb.com/bfs/static/jinkela/long/font/HarmonyOS_Regular.q.woff2
curl -O https://s1.hdslb.com/bfs/static/jinkela/long/font/HarmonyOS_Regular.r.woff2
curl -O https://s1.hdslb.com/bfs/static/jinkela/long/font/HarmonyOS_Regular.s.woff2
curl -O https://s1.hdslb.com/bfs/static/jinkela/long/font/HarmonyOS_Regular.t.woff2
curl -O https://s1.hdslb.com/bfs/static/jinkela/long/font/HarmonyOS_Regular.u.woff2
curl -O https://s1.hdslb.com/bfs/static/jinkela/long/font/HarmonyOS_Regular.v.woff2
curl -O https://s1.hdslb.com/bfs/static/jinkela/long/font/HarmonyOS_Regular.w.woff2
curl -O https://s1.hdslb.com/bfs/static/jinkela/long/font/HarmonyOS_Regular.x.woff2
curl -O https://s1.hdslb.com/bfs/static/jinkela/long/font/HarmonyOS_Regular.y.woff2
curl -O https://s1.hdslb.com/bfs/static/jinkela/long/font/HarmonyOS_Regular.z.woff2
curl -O https://s1.hdslb.com/bfs/static/jinkela/long/font/HarmonyOS_Regular.aa.woff2
curl -O https://s1.hdslb.com/bfs/static/jinkela/long/font/HarmonyOS_Regular.ab.woff2
curl -O https://s1.hdslb.com/bfs/static/jinkela/long/font/HarmonyOS_Regular.ac.woff2
curl -O https://s1.hdslb.com/bfs/static/jinkela/long/font/HarmonyOS_Regular.ad.woff2
curl -O https://s1.hdslb.com/bfs/static/jinkela/long/font/HarmonyOS_Regular.ae.woff2
curl -O https://s1.hdslb.com/bfs/static/jinkela/long/font/HarmonyOS_Regular.af.woff2
curl -O https://s1.hdslb.com/bfs/static/jinkela/long/font/HarmonyOS_Regular.ag.woff2
curl -O https://s1.hdslb.com/bfs/static/jinkela/long/font/HarmonyOS_Regular.ah.woff2
curl -O https://s1.hdslb.com/bfs/static/jinkela/long/font/HarmonyOS_Regular.ai.woff2
curl -O https://s1.hdslb.com/bfs/static/jinkela/long/font/HarmonyOS_Regular.aj.woff2
curl -O https://s1.hdslb.com/bfs/static/jinkela/long/font/HarmonyOS_Regular.ak.woff2
curl -O https://s1.hdslb.com/bfs/static/jinkela/long/font/HarmonyOS_Regular.al.woff2
curl -O https://s1.hdslb.com/bfs/static/jinkela/long/font/HarmonyOS_Regular.am.woff2
curl -O https://s1.hdslb.com/bfs/static/jinkela/long/font/HarmonyOS_Regular.an.woff2
curl -O https://s1.hdslb.com/bfs/static/jinkela/long/font/HarmonyOS_Regular.ao.woff2
curl -O https://s1.hdslb.com/bfs/static/jinkela/long/font/HarmonyOS_Regular.ap.woff2
curl -O https://s1.hdslb.com/bfs/static/jinkela/long/font/HarmonyOS_Regular.aq.woff2
curl -O https://s1.hdslb.com/bfs/static/jinkela/long/font/HarmonyOS_Regular.ar.woff2
curl -O https://s1.hdslb.com/bfs/static/jinkela/long/font/HarmonyOS_Regular.as.woff2
curl -O https://s1.hdslb.com/bfs/static/jinkela/long/font/HarmonyOS_Regular.at.woff2
curl -O https://s1.hdslb.com/bfs/static/jinkela/long/font/HarmonyOS_Regular.au.woff2
curl -O https://s1.hdslb.com/bfs/static/jinkela/long/font/HarmonyOS_Regular.av.woff2
curl -O https://s1.hdslb.com/bfs/static/jinkela/long/font/HarmonyOS_Regular.aw.woff2
curl -O https://s1.hdslb.com/bfs/static/jinkela/long/font/HarmonyOS_Regular.ax.woff2
curl -O https://s1.hdslb.com/bfs/static/jinkela/long/font/HarmonyOS_Regular.ay.woff2
curl -O https://s1.hdslb.com/bfs/static/jinkela/long/font/HarmonyOS_Regular.az.woff2
curl -O https://s1.hdslb.com/bfs/static/jinkela/long/font/HarmonyOS_Regular.a0.woff2
curl -O https://s1.hdslb.com/bfs/static/jinkela/long/font/HarmonyOS_Regular.a1.woff2
